pipeline {
    agent any

    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "jenkins-maven"
    }

    stages {
        stage('Checkout') {
            steps {
                // Get some code from a GitHub repository
                git url: 'https://github.com/Tarungagiya/jenkins_maven_project.git', branch: 'main'
            }
        }
        stage('Build') {
            steps {
                // Run Maven build
                sh 'mvn clean package'
            }
        }
        stage('Test') {
            steps {
                // Run Maven test
                sh 'mvn test'
            }
        }
        stage('Deploy') {
            steps {
                // Run Maven deploy
                sh '''
                    cd /etc/ansible/playbooks
                    ansible-playbook maven-deployment.yml
                    echo "Deployment completed"
                '''
            }
        }
    }
}
